const SECOND_IN_MILLISECONDS: number = 1000;
const MINUTE_IN_SECONDS: number = 60;
const HOUR_IN_MINUTES: number = 60;
const DAY_IN_HOURS: number = 24;
const MONTH_IN_DAYS: number = 30;

const REFRESH_TOKEN_COOKIE_TIME =
  SECOND_IN_MILLISECONDS *
  MINUTE_IN_SECONDS *
  HOUR_IN_MINUTES *
  DAY_IN_HOURS *
  MONTH_IN_DAYS;

export { REFRESH_TOKEN_COOKIE_TIME };
